### ISSUE TITLE
仿微信的那个

### ISSUE THREAD

**Issue by 15708422170** [7449/Album#3]
ui包里边的从PrevBaseActivity里边 点击原图  然后点击发送 ； 回退到 GalleryBaseActivity      的 prevLauncher 里边  UIResult.PREV_OK_FINISH_RESULT_CODE  只执行了onPrevSelectEntities  ；导致  GalleryWeChatActivity 里边  onGalleryResources  这个回调并没有改变是否为原图的状态galleryWeChatFullImage.isChecked 还是false ; onPrevSelectEntities只能传ArrayList<ScanEntity>，最好还是换成Bundle，或者在prevLauncher 调用一次onPrevToolbarFinish

**Comment by 7449** [comment]
好了，有时间的话你可以提pr

**Comment by 15708422170** [comment]
感觉可以打个版本嘛，我现在直接导了4个包，看着多有点恼火。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "7449/Album"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 晚上6:23
收件人:&nbsp;"7449/Album"<Album@noreply.github.com&gt;;
抄送:&nbsp;"546956906"<546956906@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [7449/Album] 仿微信的那个 (#3)





 
好了，有时间的话你可以提pr

**Comment by 7449** [comment]
ui:0.0.6已经更新了
