### ISSUE TITLE
图片页面

### ISSUE THREAD

**Issue by 15708422170** [7449/Album#4]
点击右上角  图片/视频  -> 选择全部视频 ->点击列表任意一个视频（比如第三个）-> 打开了本来应该是图片/视频 第三个的图
点击右上角  图片/视频  -> 选择全部视频 ->再选择 图片/视频-> 无法返回图片/视频

**Comment by 7449** [comment]
改了几个问题，第一个问题没复现出来，不知道是不是我步骤有问题，你可以看下还有没有

**Comment by 15708422170** [comment]
你提个版本呢  我直接拉代码是解决了的   感觉UI不错 我好几个项目用了你的code

**Comment by 15708422170** [comment]
> 改了几个问题，第一个问题没复现出来，不知道是不是我步骤有问题，你可以看下还有没有

你提个版本呢  我直接拉代码是解决了的   感觉UI不错 我好几个项目用了你的code

**Comment by 7449** [comment]
wechat这个library有点细节问题，可能还有一些未知的bug，你可以直接依赖这个library,UI Library已经更新了，我不是很喜欢直接static 回调，所以这里的回调都是用的继承，重写，你直接依赖library的话出了问题改起来很快,排查也快
